#!/usr/bin/with-contenv bash

cd /app/duplicati || exit

 exec \
	s6-setuidgid abc mono Duplicati.Server.exe \
	--webservice-interface=any --server-datafolder=/config --webservice-allowed-hostnames=* $CLI_ARGS
